name: Rust

on:
  push:
    branches: [ "main", "michael" ]
  pull_request:
    branches: [ "main", "michael" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build downloading_reports
      run: cargo build --example downloading_reports --verbose
    
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build downloading_reports
      run: cargo build --example downloading_reports --verbose

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build downloading_reports
      run: cargo build --example downloading_reports --verbose
